d-1-
--INSERT--
ALTER PROC PR_PERSON_INSERT
@PERSONID		INT,
@PERSONNAME		VARCHAR(50),
@SALARY			DECIMAL(8,2),
@JOININGDATE	DATETIME,
@CITY			VARCHAR(100),
@AGE			INT,
@BIRTHDATE		DATETIME
AS
BEGIN
BEGIN TRAN
INSERT INTO PERSON
(
	PERSONID,	
	PERSONNAME,	
	SALARY,		
	JOININGDATE,
	CITY,		
	AGE	,	
	BIRTHDATE	
)
VALUES
(
	@PERSONID	
	,@PERSONNAME	
	,@SALARY		
	,@JOININGDATE
	,@CITY		
	,@AGE		
	,@BIRTHDATE	
)
COMMIT TRAN
END

exec PR_PERSON_INSERT 1,'tisha',80000,'2019-09-09','rajkot',18,'2003-10-21'
select * from person

--update--
CREATE PROC PR_PERSON_UPDATE
@PERSONID		INT,
@PERSONNAME		VARCHAR(50),
@SALARY			DECIMAL(8,2),
@JOININGDATE	DATETIME,
@CITY			VARCHAR(100),
@AGE			INT,
@BIRTHDATE		DATETIME
AS
BEGIN
UPDATE PERSON SET

 PERSONNAME	 = @PERSONNAME	
,SALARY		 = @SALARY			
,JOININGDATE = @JOININGDATE
,CITY		 = @CITY		
,AGE		 = @AGE		
,BIRTHDATE	 = @BIRTHDATE
WHERE PERSONID=@PERSONID
END	

EXEC PR_PERSON_UPDATE 1,'KRISHI',70000,'2019-09-09','JAMNGAR',18,'2003-10-21' 
--DELETE--
create PROC PR_PERSON_DELETE
@PERSONID INT
AS
BEGIN
DELETE FROM PERSON 
WHERE PERSONID=@PERSONID
END

EXEC PR_PERSON_DELETE 1
SELECT * FROM PERSON 

-2-
--INSERT--
alter TRIGGER PERSON_INSERT
ON PERSON
FOR INSERT
AS
BEGIN
	DECLARE @PERSONID		INT,
			@PERSONNAME		VARCHAR(250)
	SELECT @PERSONID FROM INSERTED
	SELECT @PERSONNAME FROM INSERTED
	INSERT INTO PERSONLOG
	VALUES(	@PERSONID,
			@PERSONNAME,
			'INSERTED',
			GETDATE()
			)
END	
INSERT INTO PERSON VALUES (1,'TISHA',8000,'2025-09-09','RAJKOT',18,'2003-10-21')

--UPDATE--
ALTER TRIGGER PERSON_UPDATE
ON PERSON
FOR UPDATE
AS
BEGIN
	DECLARE @PERSONID		INT,
			@PERSONNAME		VARCHAR(250)
	SELECT @PERSONID FROM INSERTED
	SELECT @PERSONNAME FROM INSERTED
	INSERT INTO PERRSONLOG
	VALUES(	@PERSONID,
			@PERSONNAME,
			'UPDATED',
			GETDATE()
			)
END	
SELECT * FROM PersonLog

--DELETE--

CREATE TRIGGER PERSON_DELETE
ON PERSON
FOR DELETE
AS
BEGIN
	DECLARE @PERSONID		INT,
			@PERSONNAME		VARCHAR(250)
	SELECT @PERSONID FROM DELETED
	SELECT @PERSONNAME FROM DELETED
	INSERT INTO PERRSONLOG
	VALUES(	@PERSONID,
			@PERSONNAME,
			'DELETED',
			GETDATE()
			)
END

CREATE TRIGGER TR_SETAGE
ON PERSON
FOR INSERT
AS
BEGIN
DECLARE @PERSONID INT,
		@BIRTHDATE DATETIME
		SELECT @BIRTHDATE =BirthDate FROM inserted
		SELECT @PERSONID =PERSONID FROM inserted
		UPDATE PERSON SET AGE=DATEDIFF(YEAR,@BIRTHDATE,GETDATE())
		WHERE PERSONID=@PERSONID
END

ALTER PROC PR_ADD
@A INT,
@B INT,
@TOTAL INT OUTPUT
AS
BEGIN
	BEGIN TRY
		SET	@TOTAL=@A+@B
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ERRORMESSAGE
	END CATCH
END

DECLARE @TOTAL INT,
EXEC PR_ADD 12,3,@TOTAL OUTPUT;