INSERT INTO DEPARTMENT VALUES(1, 'ADMIN', 'ADM', 'A-BLOCK')
INSERT INTO DEPARTMENT VALUES(2, 'COMPUTER', 'CE', 'C-BLOCK')
INSERT INTO DEPARTMENT VALUES(3, 'CIVIL', 'CI', 'G-BLOCK')
INSERT INTO DEPARTMENT VALUES(4, 'ELECTRICAL', 'EE', 'E-BLOCK')
INSERT INTO DEPARTMENT VALUES(5, 'MECHANICAL', 'ME', 'B-BLOCK')

INSERT INTO PERSON VALUES(101, 'RAHUL TRIPATHI', 2, 56000, '2000-01-01', 'RAJKOT')
INSERT INTO PERSON VALUES(102, 'HARDIK PANDYA', 3, 18000, '2001-09-25', 'AHMEDABAD')
INSERT INTO PERSON VALUES(103, 'BHAVIN KANANI', 4, 25000, '2000-05-14', 'BARODA')
INSERT INTO PERSON VALUES(104, 'BHOOMI VAISHNAV', 1, 39000, '2005-02-08', 'RAJKOT')
INSERT INTO PERSON VALUES(105, 'ROHIT TOPIYA', 2, 17000, '2001-07-23', 'JAMNAGAR')
INSERT INTO PERSON VALUES(106, 'PRIYA MENPARA', NULL, 9000, '2000-10-18', 'AHMEDABAD')
INSERT INTO PERSON VALUES(107, 'NEHA SHARMA', 2, 34000, '2002-12-25', 'RAJKOT')
INSERT INTO PERSON VALUES(108, 'NAYAN GOSWAMI', 3, 25000, '2001-07-01', 'RAJKOT')
INSERT INTO PERSON VALUES(109, 'MEHUL BHUNDIYA', 4, 13500, '2005-01-09', 'BARODA')
INSERT INTO PERSON VALUES(110, 'MOHIT MARU', 5, 14000, '2000-05-25', 'JAMNAGAR')

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT

-1-
SELECT PERSON.PersonName, DEPARTMENT.DepartmentName, DEPARTMENT.DepartmentCode
FROM PERSON 
INNER JOIN DEPARTMENT
ON Person.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

-2-
SELECT DEPARTMENT.DepartmentName, MAX(Person.Salary), MIN(Person.Salary)
FROM PERSON 
INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DepartmentName

-3-
SELECT DEPARTMENT.DepartmentName, SUM(PERSON.SALARY) AS [TOTAL SALARY]
FROM PERSON 
INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME
HAVING SUM(PERSON.SALARY)>100000

-4-
SELECT Person.PersonName, PERSON.Salary, DEPARTMENT.DepartmentName
FROM PERSON 
LEFT OUTER JOIN DEPARTMENT
ON Person.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE Person.CITY='JAMNAGAR'

-5-
SELECT Person.PersonName
FROM PERSON 
LEFT OUTER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENT.DEPARTMENTID IS NULL

-6-
SELECT DEPARTMENT.DepartmentName, COUNT(DEPARTMENT.DEPARTMENTID)
FROM PERSON
INNER JOIN DEPARTMENT
ON Person.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DepartmentName

-7-
SELECT AVG(PERSON.Salary) AS [AVERAGE SALARY]
FROM PERSON
LEFT OUTER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
WHERE Person.CITY='AHMEDABAD'
GROUP BY Person.CITY

-8-
SELECT Person.PersonName + 'EARNS' + CAST( SALARY AS varchar) + 'FROM DEPARTMENT' + DEPARTMENT.DepartmentName + 'MONTHLY'
FROM PERSON
INNER JOIN DEPARTMENT
ON Person.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

-9-
SELECT DEPARTMENT.DepartmentName
FROM PERSON 
FULL OUTER JOIN DEPARTMENT
ON Person.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DepartmentName
HAVING COUNT(Person.DEPARTMENTID)=0

-10-
(CITY WISE)

SELECT 
	PERSON.City,
	SUM(SALARY) AS [TOTAL SALARY],
	AVG(SALARY) AS [AVG SALARY],
	MAX(SALARY) AS [MAX SALARY]
FROM PERSON
GROUP BY CITY

(DEPARTMENT WISE)

SELECT 
	DEPARTMENT.DepartmentName,
	SUM(PERSON.SALARY) AS [TOTAL SALARY],
	AVG(PERSON.SALARY) AS [AVG SALARY],
	MAX(PERSON.SALARY) AS [MAX SALARY]
FROM PERSON
INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DepartmentName

-11-
SELECT DISTINCT CITY FROM Person

-12-
SELECT 
	DEPARTMENT.DepartmentName,
	COUNT(DEPARTMENT.DEPARTMENTID)
FROM PERSON
INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
GROUP BY DEPARTMENT.DepartmentName
HAVING COUNT(DEPARTMENT.DEPARTMENTID)>2

-13-
SELECT LEFT(PERSONNAME,3) + RIGHT(CITY,3) FROM PERSON

-14-
UPDATE Person SET Salary=((Salary*10)/100)+SALARY
WHERE DEPARTMENTID = (SELECT DEPARTMENTID FROM DEPARTMENT WHERE DepartmentName='COMPUTER')

-15-
SELECT PERSONNAME FROM PERSON
WHERE (GETDATE()-JoiningDate)>365