-1-
CREATE PROC PR_DEPARTMENT_INSERT
@DEPARTMENTID INT,
@DEPARTMENTNAME VARCHAR(100)
AS
BEGIN
INSERT INTO DEPARTMENT(DEPARTMENTiD, DEPARTMENTNAME)
VALUES(@DEPARTMENTID, @DEPARTMENTNAME)
END

EXEC PR_DEPARTMENT_INSERT 1,ADMIN
EXEC PR_DEPARTMENT_INSERT 2,IT
EXEC PR_DEPARTMENT_INSERT 3,HR
EXEC PR_DEPARTMENT_INSERT 4, ACCOUNT

CREATE PROC PR_DESIGNATION_INSERT 
@DESIGNATIONID INT,
@DESIGNATIONNAME VARCHAR(100)
AS
BEGIN
INSERT INTO DESIGNATION(DESIGNATIONID, DESIGNATIONNAME)
VALUES (@DESIGNATIONID, @DESIGNATIONNAME)
END

EXEC PR_DESIGNATION_INSERT 11,JOBBER
EXEC PR_DESIGNATION_INSERT 12, WELDER
EXEC PR_DESIGNATION_INSERT 13, CLERK
EXEC PR_DESIGNATION_INSERT 14, MANAGER
EXEC PR_DESIGNATION_INSERT 15,CEO

CREATE PROC PR_PERSON_INSERT 
@FIRSTNAME VARCHAR(100),
@LASTNAME VARCHAR(100),
@SALARY DECIMAL(8,2),
@JOININGDATE DATETIME,
@DEPARTMENTID INT, 
@DESIGNATIONID INT
AS
BEGIN
INSERT INTO PERSON(FIRSTNAME,LASTNAME,SALARY,JOININGDATE,DEPARTMENTID,DESIGNATIONID)
VALUES(@FIRSTNAME,@LASTNAME,@SALARY,@JOININGDATE,@DEPARTMENTID,@DESIGNATIONID)
END

EXEC PR_PERSON_INSERT RAHUL,ANSHU,56000,'1990-01-01',1,12
EXEC PR_PERSON_INSERT HARDIK,HINSU,18000,'1990-09-25',2,11
EXEC PR_PERSON_INSERT BHAVIN,KAMANI,25000,'1991-05-14',NULL,11
EXEC PR_PERSON_INSERT BHOOMI,PATEL,39000,'2014-02-20',1,13
EXEC PR_PERSON_INSERT ROHIT,RAJGOR,17000,'1990-07-23',2,15
EXEC PR_PERSON_INSERT PRIYA,MEHTA,25000,'1990-10-18',2,NULL
EXEC PR_PERSON_INSERT NEHA,TRIVEDI,18000,'2014-02-20',3,15

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT
SELECT * FROM DESIGNATION

CREATE PROC PR_DEPARTMENT_UPDATE
@DEPARTMENTID INT,
@DEPARTMENTNAME VARCHAR(100)
AS
BEGIN
UPDATE DEPARTMENT SET DEPARTMENTNAME=@DEPARTMENTNAME
				WHERE DEPARTMENTiD=@DEPARTMENTID
END

CREATE PROC PR_DESIGNATION_UPDATE
@DESIGNATIONID INT,
@DESIGNATIONNAME VARCHAR(100)
AS
BEGIN
UPDATE DESIGNATION SET DESIGNATIONNAME=@DESIGNATIONNAME
				WHERE DESIGNATIONID=@DESIGNATIONID
END

CREATE PROC PR_PERSON_UPDATE
@WORKERID INT,
@FIRSTNAEM VARCHAR(100),
@LASTNAME VARCHAR(100),
@SALARY DECIMAL(8,2),
@JOININGDATE DATETIME,
@DEPARTMENTID INT,
@DESIGNATIONID INT
AS
BEGIN
UPDATE PERSON SET FIRSTNAME=@FIRSTNAEM,
				  LASTNAME=@LASTNAME,
				  SALARY=@SALARY,
				  JOININGDATE=@JOININGDATE,
				  DEPARTMENTID=@DEPARTMENTID,
				  DESIGNATIONID=@DESIGNATIONID
			WHERE WORKERiD=@WORKERID
END
